# Generated by Django 2.2.2 on 2019-07-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='polls',
            field=models.ManyToManyField(blank=True, null=True, to='poll.Poll'),
        ),
    ]
