# Generated by Django 2.1.7 on 2019-07-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
