# Generated by Django 2.2.2 on 2019-07-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_group_polls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='polls',
            field=models.ManyToManyField(blank=True, to='poll.Poll'),
        ),
    ]
