# Generated by Django 2.2.2 on 2019-06-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
