# Generated by Django 2.1.7 on 2019-07-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_placeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
        migrations.AlterField(
            model_name='place',
            name='name_fa',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
