# Generated by Django 2.1.7 on 2019-07-08 20:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('vote_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_choices', to='poll.Poll')),
            ],
        ),
    ]
