# Generated by Django 2.2.2 on 2019-07-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='questions',
            new_name='question',
        ),
    ]
