# Generated by Django 2.1.7 on 2019-07-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20190708_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='time_plan',
            field=models.ManyToManyField(blank=True, to='poll.TimePlan'),
        ),
    ]
