# Generated by Django 2.2.2 on 2019-07-08 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_vendor'),
        ('poll', '0002_auto_20190707_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollEventChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_count', models.IntegerField(blank=True, default=0, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_choices', to='poll.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollTextChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('choice_count', models.IntegerField(blank=True, default=0, null=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_choices', to='poll.Poll')),
            ],
        ),
        migrations.DeleteModel(
            name='PollChoice',
        ),
    ]
