# Generated by Django 2.2.2 on 2019-07-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20190708_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='vote_count',
            field=models.IntegerField(default=0, max_length=255),
        ),
    ]
