# Generated by Django 2.1.7 on 2019-07-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20190708_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='vote_count',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='time_plan',
        ),
        migrations.AddField(
            model_name='poll',
            name='time_plan',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
