# Generated by Django 2.2.2 on 2019-07-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_poll_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
